### PR TITLE
Kdnav

### PR DESCRIPTION
**Pull request by kducharme**
Features complete:

1. Side nav structure & styling added for all pages
1. Ability to click between home page and person page on the side nav
1. On the 'person page' you can click between rap sheet, newsfeed, and finances
1. Hide content button added (but not linked)

To access:

``
git fetch --all
git checkout kdstyling
``

### CODE REVIEW

**Comment by jacobxcodes** [comment]
@kducharme Looks good man. Love the side and top nav.
The only thing I can see:
1. The home page icon is missing the nav links in the top header.

**Comment by jacobxcodes** [comment]
screen shot 2018-04-16 at 8 50 00 pm

**Comment by kducharme** [comment]
@JacobAndrewSmith92 
Updated pull request to include drag and drop. To access:

``
git fetch --all
git checkout kdnav
``

**Comment by jacobxcodes** [comment]
💯

**Pull request merged**
